### ISSUE TITLE
Uncaught TypeError: i.editor.isDestroyed is not a function

### ISSUE THREAD

**Issue by RainKolwa** [xream/atom-last-buffer#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12
**Thrown From**: [last-buffer](https://github.com/xream/atom-last-buffer) package 2.0.0

### Stack Trace

Uncaught TypeError: i.editor.isDestroyed is not a function

```
At /Users/Rain/.atom/packages/last-buffer/lib/last-buffer.js:33

TypeError: i.editor.isDestroyed is not a function
    at _lodash2.default.chain.findLast.i (last-buffer.js:33:105)
    at baseFindIndex (/packages/last-buffer/node_modules/lodash/lodash.js:823:11)
    at findLastIndex (/packages/last-buffer/node_modules/lodash/lodash.js:7325:14)
    at Function.findLast (/packages/last-buffer/node_modules/lodash/lodash.js:5098:21)
    at interceptor (/packages/last-buffer/node_modules/lodash/lodash.js:16970:35)
    at Function.thru (/packages/last-buffer/node_modules/lodash/lodash.js:8812:14)
    at /packages/last-buffer/node_modules/lodash/lodash.js:4379:28
    at arrayReduce (/packages/last-buffer/node_modules/lodash/lodash.js:704:21)
    at baseWrapperValue (/packages/last-buffer/node_modules/lodash/lodash.js:4378:14)
    at LodashWrapper.wrapperValue (/packages/last-buffer/node_modules/lodash/lodash.js:9067:14)
    at Object.toggle (last-buffer.js:34:8)
    at atom-workspace.last-buffer:toggle (last-buffer.js:22:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  5x -1:31.7.0 core:confirm (input.hidden-input)
     -1:20.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  4x -1:19.3.0 core:backspace (input.hidden-input)
  4x -1:16.3.0 core:move-down (input.hidden-input)
     -1:15.2.0 core:confirm (input.hidden-input)
     -0:51.8.0 settings-view:open (input.hidden-input)
     -0:33.3.0 core:close (div.package-detail.panels-item)
     -0:30.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  5x -0:28.9.0 core:move-down (input.hidden-input)
     -0:27.5.0 core:move-up (input.hidden-input)
     -0:26.6.0 core:move-down (input.hidden-input)
     -0:25.9.0 core:move-up (input.hidden-input)
     -0:25.6.0 core:confirm (input.hidden-input)
     -0:23.9.0 core:close (div.image-view)
     -0:23.2.0 application:open (input.hidden-input)
     -0:19.1.0 last-buffer:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.13 
autocomplete-css-with-stylus-support 1.0.0 
block-comment 0.4.3 
emmet 2.4.3 
file-icons 1.7.25 
flatwhite-syntax 0.6.0 
git-time-machine 1.5.3 
language-pug 0.0.21 
language-vue 0.21.2 
language-vue-component 0.5.0 
last-buffer 2.0.0 
linter 1.11.21 
linter-eslint 8.0.0 
linter-stylint 2.2.5 
linter-stylint-h 0.0.12 
markdown-preview-plus 2.4.1 
narrow 0.37.1 
pigments 0.38.0 
project-manager 3.3.3 
react 0.16.0 
react-es6-snippets 0.3.0 
recent-files-fuzzy-finder 0.3.0 
Stylus 3.1.0 
```

**Comment by xream** [comment]
should be fixed in e1db39c
